version: '3.8'

services:
  book_generator:
    build: .
    ports:
      - "8501:8501"
    volumes:
      - ./:/app
    environment:
      - OLLAMA_HOST=ollama
      - REDIS_HOST=redis
    depends_on:
      - ollama
      - redis
  
  ollama:
    image: ollama/ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
  
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  ollama_data:
  redis_data:
